import { useMemo, useRef } from 'react'
import { PDFViewer } from '../src/index.js'
import { ViewerHarness, SAMPLE_SIGNATURE, panel, code } from './ViewerHarness.jsx'

/**
 * The sample document is generated by `bun run fixture` and is deliberately awkward:
 * page 1 is plain A4, page 2 carries a /Rotate 90 entry, and page 3 is a different
 * size. Those are exactly the cases that used to break rotation and zoom-fit.
 */
const meta = {
  title: 'PDFViewer/Basic',
  component: PDFViewer,
  tags: ['autodocs'],
  argTypes: {
    specimenAsset: {
      control: 'text',
      description: 'Single stamp image. Registered under the asset id `default`.',
      table: { category: 'Stamps' },
    },
    allowStampUpload: {
      control: 'boolean',
      description: 'Let the user pick their own image from disk.',
      table: { category: 'Stamps', defaultValue: { summary: 'true' } },
    },
    allowMultipleStamps: {
      control: 'boolean',
      description: 'When false, only one image stamp may be placed.',
      table: { category: 'Stamps', defaultValue: { summary: 'true' } },
    },
    maxStamps: {
      control: { type: 'number', min: 1, max: 20 },
      description: 'Cap on image stamps. `null` for unlimited.',
      table: { category: 'Stamps' },
    },
    rotateExportedPages: {
      control: 'boolean',
      description:
        'Whether rotating a page in the viewer also rotates it in the exported file.',
      table: { category: 'Export', defaultValue: { summary: 'true' } },
    },
    canDownload: {
      control: 'boolean',
      description: 'Disables the Download button. The harness drives this from the counts.',
      table: { category: 'Export' },
    },
    src: { control: false, table: { category: 'Document' } },
  },
  args: {
    specimenAsset: SAMPLE_SIGNATURE,
    allowStampUpload: true,
    allowMultipleStamps: true,
    maxStamps: 5,
    rotateExportedPages: true,
  },
  render: (args) => <ViewerHarness {...args} />,
}

export default meta

/**
 * Everything on by default.
 *
 * Try: place a stamp, drag it across a page boundary, draw on page 2 (which is
 * rotated), then hit Download — the exported file opens in a new tab.
 */
export const Default = {}

/**
 * Exactly one signature, which is the common e-signing setup.
 *
 * With `allowMultipleStamps: false` the Add Stamp button stops adding once a stamp is
 * on the page.
 */
export const SingleSignature = {
  args: { allowMultipleStamps: false, allowStampUpload: false },
}

/**
 * Several named stamp images plus user upload.
 *
 * `stampAssets` accepts a map or a list; the list form lets you label each entry, which
 * is what the stamp menu shows.
 */
export const MultipleStampAssets = {
  args: {
    specimenAsset: undefined,
    stampAssets: [
      { id: 'signature', label: 'Signature', src: SAMPLE_SIGNATURE },
      { id: 'approved', label: 'Approved seal', src: SAMPLE_SIGNATURE },
    ],
  },
}

/**
 * No stamp images configured at all.
 *
 * The Add Stamp button explains itself rather than silently doing nothing — but the
 * user can still upload their own, so the viewer stays useful.
 */
export const UploadOnly = {
  args: { specimenAsset: undefined, allowStampUpload: true },
}

/**
 * Viewer rotation as a viewing preference only.
 *
 * With `rotateExportedPages: false`, turning a page to read it leaves the exported
 * file in its original orientation. The default is `true`, which suits signing: someone
 * who straightens a sideways scan expects the recipient to receive it that way.
 *
 * Rotate page 1, then Download, and compare against the Default story.
 */
export const ViewOnlyRotation = {
  args: { rotateExportedPages: false },
}

/**
 * Every user-visible string replaced.
 *
 * Only the keys you pass are overridden; anything omitted stays English. Import
 * `DEFAULT_LABELS` to see the full list.
 */
export const Localised = {
  name: 'Localised (Indonesian)',
  args: {
    labels: {
      toggleThumbnails: 'Tampilkan pratinjau halaman',
      previousPage: 'Halaman sebelumnya',
      nextPage: 'Halaman berikutnya',
      pageNumber: 'Nomor halaman',
      goToPage: 'Ke halaman {page}',
      zoomIn: 'Perbesar',
      zoomOut: 'Perkecil',
      zoomAutomatic: 'Otomatis',
      zoomActualSize: 'Ukuran Asli',
      zoomPageFit: 'Muat Halaman',
      zoomPageWidth: 'Lebar Halaman',
      rotateLeft: 'Putar kiri',
      rotateRight: 'Putar kanan',
      undo: 'Urungkan',
      redo: 'Ulangi',
      draw: 'Coret bebas',
      drawSettings: 'Pengaturan coretan',
      colour: 'Warna',
      thickness: 'Ketebalan',
      opacity: 'Transparansi',
      addStamp: 'Tambah stempel',
      chooseStamp: 'Pilih gambar stempel',
      uploadImage: 'Unggah gambar…',
      addText: 'Tambah kotak teks',
      textPlaceholder: 'Ketik di sini…',
      fontSize: 'Ukuran font',
      font: 'Font',
      textColour: 'Warna teks',
      duplicate: 'Gandakan',
      delete: 'Hapus',
      download: 'Unduh',
      loading: 'Memuat dokumen…',
    },
  },
}

/**
 * Your own buttons in the toolbar, driving the imperative API.
 *
 * This is how you stamp data the viewer knows nothing about — a document number pulled
 * from your backend, a reviewer's name, a case reference. Actions render icon-only when
 * they supply an icon and fall back to their label when they do not, so nothing becomes
 * unclickable.
 */
export const CustomToolbarActions = {
  render: (args) => <CustomActionsDemo {...args} />,
}

function CustomActionsDemo(args) {
  const viewer = useRef(null)

  const actions = useMemo(
    () => [
      {
        id: 'doc-number',
        label: 'Nomor Surat',
        tooltip: 'Insert the document number',
        onClick: () =>
          viewer.current?.addTextStamp({
            text: `123/IT-DEV/${new Date().getFullYear()}`,
            fontSize: 16,
          }),
      },
      {
        id: 'reviewer',
        label: 'Reviewer',
        tooltip: 'Insert the reviewer name',
        onClick: () =>
          viewer.current?.addTextStamp({ text: 'Reviewed by: —', fontSize: 14, color: '#b91c1c' }),
      },
    ],
    []
  )

  return (
    <ViewerHarness {...args} customToolbarActions={actions} viewerRef={viewer}>
      <div style={panel}>
        Both buttons call <code style={code}>ref.addTextStamp()</code>. The new box lands on
        whichever page is in view and focuses itself.
      </div>
    </ViewerHarness>
  )
}
