import { useMemo, useRef } from 'react'
import { PDFViewer, DEFAULT_TOOLBAR_ACTIONS } from '../src/index.js'
import { ViewerHarness, SAMPLE_SIGNATURE, panel, code } from './ViewerHarness.jsx'

/**
 * The sample document is generated by `bun run fixture` and is deliberately awkward:
 * page 1 is plain A4, page 2 carries a /Rotate 90 entry, and page 3 is a different
 * size. Those are exactly the cases that used to break rotation and zoom-fit.
 */
const meta = {
  title: 'PDFViewer/Basic',
  component: PDFViewer,
  tags: ['autodocs'],
  argTypes: {
    specimenAsset: {
      control: 'text',
      description:
        'The signature image, registered under the reserved id `specimen`. The only ' +
        'thing `hasSpecimen` counts.',
      table: { category: 'Stamps' },
    },
    allowMultipleStamps: {
      control: 'boolean',
      description: 'When false, only one image stamp may be placed.',
      table: { category: 'Stamps', defaultValue: { summary: 'true' } },
    },
    maxStamps: {
      control: { type: 'number', min: 1, max: 20 },
      description: 'Cap on image stamps. `null` for unlimited.',
      table: { category: 'Stamps' },
    },
    rotateExportedPages: {
      control: 'boolean',
      description:
        'Whether rotating a page in the viewer also rotates it in the exported file.',
      table: { category: 'Export', defaultValue: { summary: 'true' } },
    },
    canDownload: {
      control: 'boolean',
      description: 'Disables the Download button. The harness drives this from the counts.',
      table: { category: 'Export' },
    },
    src: { control: false, table: { category: 'Document' } },
  },
  args: {
    specimenAsset: SAMPLE_SIGNATURE,
    allowMultipleStamps: true,
    maxStamps: 5,
    rotateExportedPages: true,
  },
  render: (args) => <ViewerHarness {...args} />,
}

export default meta

/**
 * Everything on by default.
 *
 * Try: place a stamp, drag it across a page boundary, draw on page 2 (which is
 * rotated), then hit Download — the exported file opens in a new tab.
 */
export const Default = {}

/**
 * Exactly one signature, which is the common e-signing setup.
 *
 * `allowMultipleStamps: false` stops the stamp button adding a second one, and dropping
 * `image` from the toolbar removes the user's ability to bring in an image of their own.
 *
 * Note the stamp control here has **no dropdown**: with a single configured image there
 * is nothing to choose between, so it is a plain button.
 */
export const SingleSignature = {
  args: {
    allowMultipleStamps: false,
    // Only the stamp control; no way to bring in another image.
    toolbar: { displayActions: DEFAULT_TOOLBAR_ACTIONS.filter((id) => id !== 'image') },
  },
}

/**
 * Several named stamp images.
 *
 * `stampAssets` accepts a map or a list; the list form lets you label each entry, which
 * is what the stamp menu shows. With more than one, the stamp control grows a dropdown.
 */
export const MultipleStampAssets = {
  args: {
    specimenAsset: undefined,
    stampAssets: [
      { id: 'signature', label: 'Signature', src: SAMPLE_SIGNATURE },
      { id: 'approved', label: 'Approved seal', src: SAMPLE_SIGNATURE },
    ],
  },
}

/**
 * No stamp images configured at all.
 *
 * The stamp button is disabled and says why rather than silently doing nothing. The
 * image control beside it is unaffected — a user can still bring in their own signature,
 * so the viewer stays useful with no configuration whatsoever.
 */
export const UploadOnly = {
  args: { specimenAsset: undefined },
}

/**
 * Viewer rotation as a viewing preference only.
 *
 * With `rotateExportedPages: false`, turning a page to read it leaves the exported
 * file in its original orientation. The default is `true`, which suits signing: someone
 * who straightens a sideways scan expects the recipient to receive it that way.
 *
 * Rotate page 1, then Download, and compare against the Default story.
 */
export const ViewOnlyRotation = {
  args: { rotateExportedPages: false },
}

/**
 * Every user-visible string replaced.
 *
 * Only the keys you pass are overridden; anything omitted stays English. Import
 * `DEFAULT_LABELS` to see the full list.
 */
export const Localised = {
  name: 'Localised (Indonesian)',
  args: {
    labels: {
      toggleThumbnails: 'Tampilkan pratinjau halaman',
      previousPage: 'Halaman sebelumnya',
      nextPage: 'Halaman berikutnya',
      pageNumber: 'Nomor halaman',
      goToPage: 'Ke halaman {page}',
      zoomIn: 'Perbesar',
      zoomOut: 'Perkecil',
      zoomAutomatic: 'Otomatis',
      zoomActualSize: 'Ukuran Asli',
      zoomPageFit: 'Muat Halaman',
      zoomPageWidth: 'Lebar Halaman',
      rotateLeft: 'Putar kiri',
      rotateRight: 'Putar kanan',
      undo: 'Urungkan',
      redo: 'Ulangi',
      draw: 'Coret bebas',
      drawSettings: 'Pengaturan coretan',
      colour: 'Warna',
      thickness: 'Ketebalan',
      opacity: 'Transparansi',
      addStamp: 'Tambah stempel',
      chooseStamp: 'Pilih gambar stempel',
      addImage: 'Tambah gambar sendiri',
      chooseImage: 'Pilih gambar yang sudah ditambahkan',
      uploadImage: 'Unggah gambar lain…',
      addText: 'Tambah kotak teks',
      textPlaceholder: 'Ketik di sini…',
      fontSize: 'Ukuran font',
      font: 'Font',
      textColour: 'Warna teks',
      duplicate: 'Gandakan',
      delete: 'Hapus',
      download: 'Unduh',
      loading: 'Memuat dokumen…',
    },
  },
}

/**
 * Your own buttons in the toolbar, driving the imperative API.
 *
 * This is how you stamp data the viewer knows nothing about — a document number pulled
 * from your backend, a reviewer's name, a case reference. Actions render icon-only when
 * they supply an icon and fall back to their label when they do not, so nothing becomes
 * unclickable.
 */
export const CustomToolbarActions = {
  render: (args) => <CustomActionsDemo {...args} />,
}

function CustomActionsDemo(args) {
  const viewer = useRef(null)

  const actions = useMemo(
    () => [
      {
        id: 'doc-number',
        label: 'Nomor Surat',
        tooltip: 'Insert the document number',
        onClick: () =>
          viewer.current?.addTextStamp({
            text: `123/IT-DEV/${new Date().getFullYear()}`,
            fontSize: 16,
          }),
      },
      {
        id: 'reviewer',
        label: 'Reviewer',
        tooltip: 'Insert the reviewer name',
        onClick: () =>
          viewer.current?.addTextStamp({ text: 'Reviewed by: —', fontSize: 14, color: '#b91c1c' }),
      },
    ],
    []
  )

  return (
    <ViewerHarness {...args} toolbar={{ customToolbarActions: actions }} viewerRef={viewer}>
      <div style={panel}>
        Both buttons call <code style={code}>ref.addTextStamp()</code>. The new box lands on
        whichever page is in view and focuses itself. With no{' '}
        <code style={code}>displayActions</code>, they are appended after the built-in controls.
      </div>
    </ViewerHarness>
  )
}

/**
 * **Working with objects on the page.**
 *
 * A few of these are not guessable, so they are worth trying here before you write help
 * text for your own users.
 *
 * - **Move** — drag it. Anywhere on the object, text boxes included.
 * - **Edit text** — **double-click** the box. `Escape` or a click away stops.
 *   A box you have just created skips this and opens ready to type.
 * - **Resize** — drag a corner or edge handle.
 * - **Rotate** — drag the round handle above the object; hold `Shift` to snap to 15°.
 *   The small toolbar hides while you turn and comes back on release.
 * - **Across pages** — drag an object onto another page and it is reassigned to it.
 *
 * Text takes a double-click because a single click drags — the same trade pdf.js and
 * every canvas editor makes. Undo covers all of it, one step per gesture.
 */
export const Interactions = {
  render: (args) => (
    <ViewerHarness {...args}>
      <div style={panel}>
        Try: add a text box, click elsewhere to deselect, then drag it. Double-click to
        type again. Rotate it and watch the toolbar step out of the way.
      </div>
    </ViewerHarness>
  ),
}

/**
 * **Stamps and images are two separate controls.**
 *
 * The stamp button places what *you* configured through `specimenAsset` and
 * `stampAssets`. The image button beside it lets the *user* bring in their own — it
 * opens a file picker, and anything they add collects behind its caret so it can be
 * placed again without picking the file twice.
 *
 * They used to be one control, which forced a dropdown onto the stamp button even with a
 * single signature configured, because the upload entry always had to live behind it.
 * Here there are two configured stamps, so the stamp dropdown is genuinely useful —
 * compare with **Single signature**, where it is a plain button.
 *
 * Only stamps placed from `specimenAsset` count towards `hasSpecimen`; a seal and an
 * uploaded image do not. See **Integration → Specimen vs Annotation**.
 */
export const StampsAndImages = {
  args: {
    stampAssets: [{ id: 'seal', label: 'Approved seal', src: SAMPLE_SIGNATURE }],
  },
  render: (args) => (
    <ViewerHarness {...args}>
      <div style={panel}>
        Stamp button: the signature and the seal. Image button: whatever you upload. To
        forbid uploads entirely, drop <code style={code}>&apos;image&apos;</code> from{' '}
        <code style={code}>displayActions</code>.
      </div>
    </ViewerHarness>
  ),
}
